### ISSUE TITLE
The LA-Transformer test code don't "remove gallery samples that have the same pid and camid with query"

### ISSUE THREAD

**Issue by agangzz** [SiddhantKapil/LA-Transformer#3]
The LA-Transformer test code seems not "remove gallery samples that have the same pid and camid with query" when calculate rank1/rankn/mAP?
 
such as https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/metrics/rank.py

**Comment by SiddhantKapil** [comment]
We are planning to add other datasets results by August first week. We will add this evaluation as well. Thanks for the feedback.

**Comment by agangzz** [comment]
When evaluation don't "remove gallery samples that have the same pid and camid with query" , the rank1/rankn/mAP may not objective.

**Comment by sophieyl** [comment]
I replaced the evaluation code and the results are quite poor.
mAP: 0.6875 rank1: 0.8605 rank3: 0.9198 rank5: 0.9403 rank10: 0.9638
Look forward to your updated, see whether if something wrong happened.

@SiddhantKapil

**Comment by michuanhaohao** [comment]
I also observe that camera IDs are not used to compute CMC and mAP. I think the accuracy scores are wrong.
