### ISSUE TITLE
Issuse about paper Equation and implementation.

### ISSUE THREAD

**Issue by Xanadu12138** [SiddhantKapil/LA-Transformer#4]
Thanks for the great work! However, I find there is a slightly diffierence in the eq.6 in paper and code implmentation.
In model.py line 116-119
```python
# Add global cls token to each local token 
for i in range(self.part):
    out = torch.mul(x[:, i, :], self.lmbd)
    x[:,i,:] = torch.div(torch.add(cls_token_out.squeeze(),out), 1+self.lmbd)
```
Nevertheless, in the paper the equation 6.
![image](https://user-images.githubusercontent.com/45411494/126276591-9745e1e1-b4c8-4bf0-9b94-41da77b6db82.png)
The numerator should be Q_j + lmbd * G instead of Q_j * lmbd + G in code.
Otherwise I wrongly understand the code's meaning. Please let me know if I am wrong about it.

**Comment by SiddhantKapil** [comment]
Thanks for pointing out, we were performing some experiments by inverting lambda. We will correct it in the next update.

**Comment by viet2411** [comment]
Hello,

I also noticed that the value of lmbd in code implementation was 8, not 0.8 like in the paper.
Was there anything wrong here, or did I misunderstand the code? Please correct me if I'm wrong.

Best regards.
